
heighliner:
  build: .
  command: "supervisor index.js"
  volumes:
    - .:/usr/src/app/
  links:
    - mySQL
    - mongoDB
  ports:
    - "80:8080"

mySQL:
  image: mysql:5.5
  volumes:
    - ./util/db/mysql/:/etc/mysql/conf.d
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: ee_local
    MYSQL_USER: root

mongoDB:
  image: mongo:latest
  ports:
    - "27017:27017"
